# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

# import wx_admin_pb2 as wx__admin__pb2
from ..proto import wx_admin_pb2 as wx__admin__pb2

class WXAdminStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SubscribeScanLogin = channel.unary_unary(
                '/opb.WXAdmin/SubscribeScanLogin',
                request_serializer=wx__admin__pb2.SubscribeScanLoginRequest.SerializeToString,
                response_deserializer=wx__admin__pb2.SubscribeScanLoginResponse.FromString,
                )


class WXAdminServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SubscribeScanLogin(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WXAdminServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SubscribeScanLogin': grpc.unary_unary_rpc_method_handler(
                    servicer.SubscribeScanLogin,
                    request_deserializer=wx__admin__pb2.SubscribeScanLoginRequest.FromString,
                    response_serializer=wx__admin__pb2.SubscribeScanLoginResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'opb.WXAdmin', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class WXAdmin(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SubscribeScanLogin(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/opb.WXAdmin/SubscribeScanLogin',
            wx__admin__pb2.SubscribeScanLoginRequest.SerializeToString,
            wx__admin__pb2.SubscribeScanLoginResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
