# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: wx_admin.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='wx_admin.proto',
  package='opb',
  syntax='proto3',
  serialized_options=b'Z\005.;opb',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0ewx_admin.proto\x12\x03opb\"\x87\x01\n\x19SubscribeScanLoginRequest\x12\x12\n\nToUserName\x18\x01 \x01(\t\x12\x14\n\x0c\x46romUserName\x18\x02 \x01(\t\x12\x0f\n\x07MsgType\x18\x03 \x01(\t\x12\r\n\x05\x45vent\x18\x04 \x01(\t\x12\x10\n\x08\x45ventKey\x18\x05 \x01(\t\x12\x0e\n\x06Ticket\x18\x06 \x01(\t\"5\n\x1aSubscribeScanLoginResponse\x12\n\n\x02OK\x18\x01 \x01(\x08\x12\x0b\n\x03Msg\x18\x02 \x01(\t2b\n\x07WXAdmin\x12W\n\x12SubscribeScanLogin\x12\x1e.opb.SubscribeScanLoginRequest\x1a\x1f.opb.SubscribeScanLoginResponse\"\x00\x42\x07Z\x05.;opbb\x06proto3'
)




_SUBSCRIBESCANLOGINREQUEST = _descriptor.Descriptor(
  name='SubscribeScanLoginRequest',
  full_name='opb.SubscribeScanLoginRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ToUserName', full_name='opb.SubscribeScanLoginRequest.ToUserName', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='FromUserName', full_name='opb.SubscribeScanLoginRequest.FromUserName', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='MsgType', full_name='opb.SubscribeScanLoginRequest.MsgType', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Event', full_name='opb.SubscribeScanLoginRequest.Event', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='EventKey', full_name='opb.SubscribeScanLoginRequest.EventKey', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Ticket', full_name='opb.SubscribeScanLoginRequest.Ticket', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=159,
)


_SUBSCRIBESCANLOGINRESPONSE = _descriptor.Descriptor(
  name='SubscribeScanLoginResponse',
  full_name='opb.SubscribeScanLoginResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='OK', full_name='opb.SubscribeScanLoginResponse.OK', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Msg', full_name='opb.SubscribeScanLoginResponse.Msg', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=161,
  serialized_end=214,
)

DESCRIPTOR.message_types_by_name['SubscribeScanLoginRequest'] = _SUBSCRIBESCANLOGINREQUEST
DESCRIPTOR.message_types_by_name['SubscribeScanLoginResponse'] = _SUBSCRIBESCANLOGINRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SubscribeScanLoginRequest = _reflection.GeneratedProtocolMessageType('SubscribeScanLoginRequest', (_message.Message,), {
  'DESCRIPTOR' : _SUBSCRIBESCANLOGINREQUEST,
  '__module__' : 'wx_admin_pb2'
  # @@protoc_insertion_point(class_scope:opb.SubscribeScanLoginRequest)
  })
_sym_db.RegisterMessage(SubscribeScanLoginRequest)

SubscribeScanLoginResponse = _reflection.GeneratedProtocolMessageType('SubscribeScanLoginResponse', (_message.Message,), {
  'DESCRIPTOR' : _SUBSCRIBESCANLOGINRESPONSE,
  '__module__' : 'wx_admin_pb2'
  # @@protoc_insertion_point(class_scope:opb.SubscribeScanLoginResponse)
  })
_sym_db.RegisterMessage(SubscribeScanLoginResponse)


DESCRIPTOR._options = None

_WXADMIN = _descriptor.ServiceDescriptor(
  name='WXAdmin',
  full_name='opb.WXAdmin',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=216,
  serialized_end=314,
  methods=[
  _descriptor.MethodDescriptor(
    name='SubscribeScanLogin',
    full_name='opb.WXAdmin.SubscribeScanLogin',
    index=0,
    containing_service=None,
    input_type=_SUBSCRIBESCANLOGINREQUEST,
    output_type=_SUBSCRIBESCANLOGINRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_WXADMIN)

DESCRIPTOR.services_by_name['WXAdmin'] = _WXADMIN

# @@protoc_insertion_point(module_scope)
