name: dev

env:
  DOCKER_TAG: dev.1.1.${{ github.run_id }}
  APP_NAME: ${{ github.event.repository.name }}
  TAG: ${{ secrets.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}:dev.1.1.${{ github.run_id }}
  LATEST_TAG: ${{ secrets.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}:dev.latest
  REPO: ${{ secrets.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}

on:
  push:
    branches:
      - 'develop'

jobs:

  buildAndPush:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          platforms: linux/amd64
          tags: ${{ env.TAG }},${{ env.LATEST_TAG }}